# Generated by Django 2.2.6 on 2019-11-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentSearchApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='availability_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='miles_from_campus',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
