# Generated by Django 2.2.6 on 2019-12-17 02:15

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(null=True)),
                ('address', models.CharField(max_length=100)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('num_bedrooms', models.PositiveIntegerField()),
                ('num_bathrooms', models.FloatField()),
                ('image_url', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('miles_from_campus', models.FloatField(null=True)),
                ('area_of_campus', models.CharField(choices=[('N', 'North Campus'), ('S', 'South Campus')], max_length=10)),
                ('url', models.CharField(max_length=1000)),
                ('availability_date', models.DateField(null=True)),
                ('active', models.BooleanField()),
            ],
            managers=[
                ('listings', django.db.models.manager.Manager()),
            ],
        ),
    ]
