# Generated by Django 2.2.6 on 2019-12-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffCampusRestApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='scraper',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
