# Generated by Django 2.2.6 on 2019-12-19 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffCampusRestApi', '0002_listing_scraper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='area_of_campus',
        ),
        migrations.AddField(
            model_name='listing',
            name='availability_mode',
            field=models.CharField(choices=[('S', 'Season'), ('M', 'Month'), ('N', 'Now'), ('-', 'None'), ('D', 'Date')], default='D', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='date_found',
            field=models.DateField(default=datetime.datetime.now().date()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='date_updated',
            field=models.DateField(default=datetime.datetime.now().date()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='unit',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=64, null=True)),
                ('favorites', models.ManyToManyField(to='OffCampusRestApi.Listing')),
            ],
        ),
    ]
