# Generated by Django 2.2.6 on 2020-03-17 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OffCampusRestApi', '0004_auto_20200317_1936'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='listing',
        #     old_name='date_found',
        #     new_name='date_created',
        # ),
    ]
