# Generated by Django 2.2.6 on 2019-12-22 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OffCampusRestApi', '0005_auto_20191221_1959'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='listing',
            managers=[
            ],
        ),
    ]
