# Generated by Django 2.2.6 on 2020-03-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OffCampusRestApi', '0005_auto_20200317_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='num_bathrooms',
            new_name='bath',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='num_bedrooms',
            new_name='beds',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='image_url',
            new_name='image',
        ),
    ]
