# Generated by Django 2.2.6 on 2020-05-11 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OffCampusRestApi', '0006_auto_20200319_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bath',
            new_name='baths',
        ),
    ]
