# Generated by Django 2.2.6 on 2019-12-22 01:33

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('OffCampusRestApi', '0006_auto_20191221_2031'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='listing',
            managers=[
                ('listings', django.db.models.manager.Manager()),
            ],
        ),
    ]
