# Generated by Django 2.2.6 on 2020-05-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffCampusRestApi', '0009_auto_20200513_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='scraper',
            field=models.CharField(max_length=100),
        ),
    ]
