# Generated by Django 2.2.6 on 2020-09-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffCampusRestApi', '0011_listing_pretty_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='pretty_address',
        ),
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='state',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='listing',
            name='street_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='street_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='street_prefix',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='street_range',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='listing',
            name='street_type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
