# Generated by Django 2.2.6 on 2020-05-18 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OffCampusRestApi', '0005_auto_20191221_1959'),
        ('OffCampusRestApi', '0011_listing_pretty_address'),
    ]

    operations = [
    ]
