# Generated by Django 2.2.6 on 2020-05-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffCampusRestApi', '0012_merge_20200518_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='date_created',
            new_name='date_found',
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='scraper',
            field=models.CharField(max_length=100),
        ),
    ]
