# Generated by Django 2.2.6 on 2020-06-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OffCampusRestApi', '0014_auto_20200518_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=255)),
                ('liked_listings', models.ManyToManyField(to='OffCampusRestApi.Listing')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
