# Generated by Django 2.2.6 on 2020-06-05 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OffCampusRestApi', '0015_auto_20200604_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googleuser',
            old_name='liked_listings',
            new_name='favorites',
        ),
    ]
